- id: '1635488749946'
  alias: Lights dim kitchen when Roku plays Plex
  description: ''
  trigger:
  - platform: device
    device_id: 0156d3b59488af26464984e53213dda5
    domain: media_player
    entity_id: media_player.plex_plex_for_roku_roku_ultra_yp004n277326
    type: playing
    id: roku plays plex
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.tv_lights
    data: {}
  mode: single
- id: '1635489013090'
  alias: Lights brighten kitchen when Roku pauses or stops Plex
  description: ''
  trigger:
  - platform: device
    device_id: 0156d3b59488af26464984e53213dda5
    domain: media_player
    entity_id: media_player.plex_plex_for_roku_roku_ultra_yp004n277326
    type: turned_off
    id: Roku off
    for:
      hours: 0
      minutes: 0
      seconds: 1
  - platform: device
    device_id: 0156d3b59488af26464984e53213dda5
    domain: media_player
    entity_id: media_player.plex_plex_for_roku_roku_ultra_yp004n277326
    type: paused
    id: Roku pause
    for:
      hours: 0
      minutes: 0
      seconds: 1
  - platform: device
    device_id: 0156d3b59488af26464984e53213dda5
    domain: media_player
    entity_id: media_player.plex_plex_for_roku_roku_ultra_yp004n277326
    type: idle
    id: Roku idle
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.normal_lights
    data: {}
  mode: single
- id: '1635857890124'
  alias: 'Lights Turn on the lights when I get home '
  description: ''
  trigger:
  - platform: zone
    entity_id: person.matt_petersen
    zone: zone.home
    event: enter
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - type: turn_on
    device_id: e9abdc35380d462a53fb363177e7e95d
    entity_id: light.hue_colour_lamp_1
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 966e58820dfa8de085788fee6093c500
    entity_id: light.hue_color_lamp_2
    domain: light
    brightness_pct: 100
  - type: turn_on
    device_id: 1c4f343dda0c3279c2c0457a07fba067
    entity_id: light.hue_color_lamp_3
    domain: light
    brightness_pct: 100
  mode: single
- id: '1636931873459'
  alias: Notify when matt home
  description: send a telegram message when someone enters geofence for home
  trigger:
  - platform: zone
    entity_id: person.matt_petersen
    zone: zone.home
    event: enter
    id: '1'
  condition: []
  action:
  - service: telegram_bot.send_message
    data:
      message: Matt just got home
      title: Arrived home
  mode: single
- id: '1642253769934'
  alias: Lights Switch MBR Toggle
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: e7be9b9fcb940cba3f50b066da8f878a
    type: action
    subtype: 'on'
    discovery_id: 0x8cf681fffe48be79 action_on
    id: ms_1
  condition: []
  action:
  - type: toggle
    device_id: 8937f8ddb86a0ee69ebaf4f4d0c16409
    entity_id: light.bedroom_lights
    domain: light
  mode: single
- id: '1642253897406'
  alias: Lights Switch MBR Toggle All
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: e7be9b9fcb940cba3f50b066da8f878a
    type: action
    subtype: 'off'
    discovery_id: 0x8cf681fffe48be79 action_off
    id: ms_1
  condition: []
  action:
  - type: toggle
    device_id: efb8e6b4a5858da13eecf853a1445d4a
    entity_id: light.all_lights_2
    domain: light
  mode: single
- id: '1642254159854'
  alias: Lights Switch MBR Brighten
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: e7be9b9fcb940cba3f50b066da8f878a
    type: action
    subtype: brightness_move_up
    discovery_id: 0x8cf681fffe48be79 action_brightness_move_up
    id: sw_1
  condition: []
  action:
  - device_id: 8937f8ddb86a0ee69ebaf4f4d0c16409
    domain: light
    entity_id: light.bedroom_lights
    type: brightness_increase
  mode: single
- id: '1642254273054'
  alias: Lights Switch MBR Dim
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: e7be9b9fcb940cba3f50b066da8f878a
    type: action
    subtype: brightness_move_down
    discovery_id: 0x8cf681fffe48be79 action_brightness_move_down
    id: sw_1
  condition: []
  action:
  - device_id: 8937f8ddb86a0ee69ebaf4f4d0c16409
    domain: light
    entity_id: light.bedroom_lights
    type: brightness_decrease
  mode: single
- id: '1642985788012'
  alias: Housekeeping purge recorder db
  description: Purge all recorder history older than last 7 days, and restart home
    assistant
  trigger:
  - platform: time
    id: daily_housekeeping
    at: 02:00
  condition: []
  action:
  - service: recorder.purge
    data:
      keep_days: 7
      repack: true
  - service: homeassistant.restart
    data: {}
  mode: single
- id: '1643033279656'
  alias: Housekeeping Weekly Pocket Money
  description: pay kids $10, providing PM is not suspended
  trigger:
  - platform: time
    at: input_datetime.monday_mornings
  condition: []
  action:
  - service: script.script_pocketmoney_increment
    data:
      pocketmoney_payee: dan
  - service: script.script_pocketmoney_increment
    data:
      pocketmoney_payee: laura
  - service: input_datetime.set_datetime
    target:
      entity_id: input_datetime.monday_mornings
    data:
      time: 07:00:00
      date: '{{ (now().timestamp() + ((7 - now().weekday()) *86400)) | int | timestamp_custom("%Y-%m-%d")
        }}'
  - service: telegram_bot.send_message
    data:
      title: <h2>Pocket Money Processed</h2>
      target: -418902609
      message: '<b>Laura:</b> ${{ states(''counter.pocketmoney_laura'') }} (Active:
        {{ states(''input_boolean.pocketmoney_laura_active'') }})

        <b>Dan:</b> ${{ states(''counter.pocketmoney_dan'') }} (Active: {{ states(''input_boolean.pocketmoney_dan_active'')
        }})

        <b>Next due:</b> {{ states(''input_datetime.monday_mornings'') }} '
      parse_mode: html
  mode: single
- id: '1644291880377'
  alias: Notify when Dan leaving home
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.people_home
    to: '0'
  condition: []
  action:
  - scene: scene.all_off
  mode: single
- id: '1644608882905'
  alias: HadesPC Switch Portable PC Rickroll joke
  description: Rickroll button :)
  trigger:
  - platform: device
    domain: mqtt
    device_id: bb79ca7b53dce058399377781a4dd675
    type: action
    subtype: 'on'
    discovery_id: 0x0c4314fffeb0734e action_on
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/haydescanyon/commands/run
      payload: '{ "command": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
        "args": "https://www.youtube.com/watch?v=oHg5SJYRHA0", "path": "C:\\Program
        Files (x86)\\Google\\Chrome\\Application", "user": "", "visible": true, "fallback":
        true }'
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/haydescanyon/commands/notify
      payload: '{ "title": "HAHA!! :)", "message": "Loooooooooser!!!", "iconUrl":
        "", "launchParams": "" }'
  mode: single
- id: '1644614058509'
  alias: HadesPC Switch portable Lock computer
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: bb79ca7b53dce058399377781a4dd675
    type: action
    subtype: 'off'
    discovery_id: 0x0c4314fffeb0734e action_off
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/haydescanyon/commands/lock
  mode: single
- id: '1644773366189'
  alias: test send notifification
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.trst_toggle
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      device_id: ee713bfc1a6e3b92dcadff4a81f0b208
  mode: single
- id: '1644778728335'
  alias: Notify Check batteries < 20%
  description: ''
  use_blueprint:
    path: Sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '19:00:00'
      actions:
      - service: telegram_bot.send_message
        data:
          title: Warning
          message: Low batteries for {{sensors}}
      threshold: 20
